language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "chenminhao"
  - git config user.email "18219116770@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${myblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/chenminhao/chenminhao.github.io.git